import pandas as pd
from statsmodels.stats.proportion import proportions_ztest

def run_cli_analyzer(file_path):
    print(f"--- Loading data from {file_path} ---\n")
    
    try:
        # 1. Load the raw data
        df = pd.read_csv(file_path)
    except FileNotFoundError:
        print("Error: Could not find the CSV file. Did you run the mock data generator?")
        return

    # 2. Group data by 'Ad Name' and sum up the performance metrics
    print("Aggregating metrics...")
    metrics = df.groupby('Ad Name')[['Impressions', 'Clicks', 'Conversions']].sum()

    # 3. Calculate core SEM metrics (Click-Through Rate & Conversion Rate)
    metrics['CTR'] = (metrics['Clicks'] / metrics['Impressions']) * 100
    metrics['CVR'] = (metrics['Conversions'] / metrics['Clicks']) * 100

    # Format the output to look clean in the terminal
    formatted_metrics = metrics.copy()
    formatted_metrics['CTR'] = formatted_metrics['CTR'].map('{:.2f}%'.format)
    formatted_metrics['CVR'] = formatted_metrics['CVR'].map('{:.2f}%'.format)
    
    print("\n=== OVERALL PERFORMANCE ===")
    print(formatted_metrics[['Impressions', 'Clicks', 'Conversions', 'CTR', 'CVR']])
    print("===========================\n")

    # 4. Statistical Significance Testing (A/B Test Logic)
    print("--- Running Z-Test for Statistical Significance ---")
    
    # We need arrays of the conversions and clicks to run the proportions test
    conversions = metrics['Conversions'].values
    clicks = metrics['Clicks'].values
    ad_names = metrics.index.tolist()

    if len(ad_names) != 2:
        print("Error: This analyzer currently expects exactly 2 ad variations.")
        return

    # Perform the Z-test
    # This checks if the difference in Conversion Rates is mathematically real or just noise
    stat, p_value = proportions_ztest(count=conversions, nobs=clicks)

    print(f"Comparing: '{ad_names[0]}' vs '{ad_names[1]}'")
    print(f"P-Value: {p_value:.4f}")

    # 5. Business Logic: Interpret the stats for the user
    # In marketing, a p-value < 0.05 means 95% confidence (industry standard)
    if p_value < 0.05:
        # Find which ad actually had the higher CVR
        winner_idx = metrics['CVR'].argmax()
        winner_name = ad_names[winner_idx]
        
        print(f"\n✅ RESULT: STATISTICALLY SIGNIFICANT WINNER FOUND!")
        print(f"🏆 The winner is: {winner_name}")
        print("Action: You can confidently pause the losing ad variation.")
    else:
        print("\n⏳ RESULT: NO CLEAR WINNER YET.")
        print("Action: The difference in performance is not statistically significant. Keep running the test.")

if __name__ == "__main__":
    # Point this to the file generated by your previous script
    run_cli_analyzer("mock_google_ads_data5.csv")